[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4", "tox"]

[tool.black]
line-length = 79

[tool.setuptools_scm]
write_to = "pokr/_version.py"
local_scheme = "dirty-tag"
fallback_version = "0.0.0"
